import {
  Poppins,
  Mulish,
} from "next/font/google";
import "./globals.css";
import Header from "@/components-ida/Header";
import Footer from "@/Kia-Components/Footer";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["900"],
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppinsSans.variable} ${mulish.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
